// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtfHnrpfvIZrHIyeHM8N-JHghoO6HP3bE',
    appId: '1:1076571659298:web:d0c240371c4b716c15be7b',
    messagingSenderId: '1076571659298',
    projectId: 'trailmate-8d03b',
    authDomain: 'trailmate-8d03b.firebaseapp.com',
    storageBucket: 'trailmate-8d03b.appspot.com',
    measurementId: 'G-F5V9JWC95X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMnFaJqXUZ496-WWs_Mq2j5Vkk-UVDWAg',
    appId: '1:1076571659298:android:429b56c3070737d415be7b',
    messagingSenderId: '1076571659298',
    projectId: 'trailmate-8d03b',
    storageBucket: 'trailmate-8d03b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeXrIRlCarvCZ7Sx5ee2iyiPCZHcf0nhE',
    appId: '1:1076571659298:ios:44e79c15bda3c49415be7b',
    messagingSenderId: '1076571659298',
    projectId: 'trailmate-8d03b',
    storageBucket: 'trailmate-8d03b.appspot.com',
    iosClientId: '1076571659298-3ko3um08r0irm7qio1jtl3fh48upa5et.apps.googleusercontent.com',
    iosBundleId: 'munozme.mackechr.sheridan.trailmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeXrIRlCarvCZ7Sx5ee2iyiPCZHcf0nhE',
    appId: '1:1076571659298:ios:44e79c15bda3c49415be7b',
    messagingSenderId: '1076571659298',
    projectId: 'trailmate-8d03b',
    storageBucket: 'trailmate-8d03b.appspot.com',
    iosClientId: '1076571659298-3ko3um08r0irm7qio1jtl3fh48upa5et.apps.googleusercontent.com',
    iosBundleId: 'munozme.mackechr.sheridan.trailmate',
  );
}
